# -*- coding: utf-8 -*-
"""Proyek Technical Test - Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aV4bpHzbu5TXACqJ8yWj69p7KkpJjeFb

# Proyek Analisis Data - Coordinator Trainee Service Quality

*   Nama : Amrul Fadhil Yofan
*   Email : amrul.yofan@gmail.com

## Menganalisis Data Terkait Service Quality dan Menentukan Pertanyaan Bisnis

Berikut beberapa analisis yang dapat dilakukan:


*   Persebaran toko pada setiap wilayah dan distribusi faktor masalah pada setiap divisi
*   Analisis waktu penyelesaian masalah serta identifikasi faktor penyebab masalah
*   Analisis tingkat kepuasan dan pengaruh faktor masalah terhadap tingkat kepuasan pelanggan
*   Hubungan antara waktu penyelesaian masalah dengan tingkat kepuasan pelanggan
*   Perbandingan rata-rata tingkat kepuasan berdasarkan wilayah dan divisi

Diperoleh kemungkinan beberapa pertanyaan sebagai berikut:


*   Wilayah/cabang manakah yang memiliki toko paling banyak atau paling sedikit?
*   Apa penyebab masalah yang paling banyak dihadapi oleh masing-masing divisi?
*   Bagaimana distribusi penyebab masalah pada setiap divisi?
*   Divisi manakah yang menangani kasus masalah paling banyak?
*   Bagaimana distribusi data waktu penyelesaian masalah untuk semua kategori? Apakah relatif cepat atau lambat?
*   Apa penyebab masalah yang memiliki frekuensi paling banyak atau paling sedikit?
*   Bagaimana persentase atau perbandingan tingkat kepuasan pelanggan?
*   Bagaimana distribusi faktor masalah terhadap tingkat kepuasan pelanggan?
*   Bagaimana korelasi/hubungan antara waktu penyelesaian masalah dengan tingkat kepuasan pelanggan?
*   Wilayah/cabang manakah yang memiliki rata-rata tingkat kepuasan tertinggi/terendah?
*   Divisi manakah yang memiliki rata-rata tingkat kepuasan tertinggi/terendah?

### Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import TwoSlopeNorm

"""## Data Wrangling

### Gathering Data

Dilakukan proses pengumpulan data dan menyiapkan dataset supaya memudahkan proses analisis data.
"""

data = pd.read_excel("dataset.xlsx")
data.head(10)

df = data.drop(data.index[0])
df.columns = df.iloc[0].values
df = df[1:].reset_index(drop=True)
df

"""### Assessing Data

Dilakukan proses assessing data untuk melihat apakah ada kesalahan-kesalahan data yang perlu diperbaiki. Terlebih dahulu ditinjau informasi-informasi yang ada pada data tersebut.
"""

df.info()

df.isna().sum()

df.describe()

print("Jumlah duplikasi tabel: ", df.duplicated().sum())

"""Diperoleh hasil identifikasi masalah pada data, yakni sebagai berikut."""

df_table_assess = pd.DataFrame({
    "Data Type": ['Terdapat kesalahan tipe data untuk kolom TGL_PROB, TGL_PROGRESS, TGL_SOLVE, dan TGL_CLOSE (seharusnya bertipe data datetime) serta tipe data untuk kolom WAKTU_PENYELESAIAN, TARGET_HARI, ACH_SLA dan TINGKAT_KEPUASAN (seharusnya bertipe data integer)'],
    "Missing Value": ['Terdapat entri data kosong pada kolom TGL_PROGRESS'],
    "Duplicate Data": ['-'],
    "Inaccurate Value": ['-']
})
df_table_assess.style \
  .format(precision=3, thousands=".", decimal=",") \
  .format_index(str.upper, axis=1) \
  .relabel_index(["df"], axis=0)

"""### Cleaning Data

Diperoleh dua permasalahan, yaitu terkait kesalahan tipe data dan eksistensi missing value.
"""

df["TGL_PROB"] = pd.to_datetime(df["TGL_PROB"])
df["TGL_PROGRESS"] = pd.to_datetime(df["TGL_PROGRESS"])
df["TGL_SOLVE"] = pd.to_datetime(df["TGL_SOLVE"])
df["TGL_CLOSE"] = pd.to_datetime(df["TGL_CLOSE"])

df["WAKTU_PENYELESAIAN"] = df["WAKTU_PENYELESAIAN"].astype(int)
df["TARGET_HARI"] = df["TARGET_HARI"].astype(int)
df["ACH_SLA"] = df["ACH_SLA"].astype(int)
df["TINGKAT_KEPUASAN"] = df["TINGKAT_KEPUASAN"].astype(int)

df.info()

missing_values = df[df.isna().any(axis=1)]
missing_values

"""Karena terdapat 1 feature yang memuat data kosong dan hanya ada 3 entri kosong, maka hal ini cukup dibiarkan saja."""



"""## Exploratory Data Analysis (EDA)

### Deskripsi Data

Ditinjau beberapa deskripsi data secara statistik sebagai berikut.
"""

df.describe(include="all")

"""### Menghitung Jumlah Data Pada Beberapa Kolom

Ditinjau jumlah data pada beberapa kolom.
"""

df["TINGKAT_KEPUASAN"].value_counts()

df["NAMA_CABANG"].value_counts()

df["DIVISI"].value_counts()

df["WAKTU_PENYELESAIAN"].value_counts()

df["MASALAH"].value_counts().head(10)

df["TARGET_HARI"].value_counts()

df["FAKTOR_PROBLEM"].value_counts()

"""### Binning Waktu Penyelesaian Masalah"""

plt.hist(df['WAKTU_PENYELESAIAN'])
plt.show()

batas_bin_wp = [-1,5,20,500]
kategori_wp = ['0-5','6-20','21-500']
df1 = (pd.cut(df['WAKTU_PENYELESAIAN'], bins=batas_bin_wp, labels=kategori_wp)).copy()
df1

plt.hist(df1)
plt.show()

"""## Visualization and Explanatory Analysis

### Persebaran toko pada setiap wilayah



*   Wilayah/cabang manakah yang memiliki toko paling banyak atau paling sedikit?

Dibentuk diagram batang untuk melihat persebaran toko pada setiap wilayah/cabang sebagai berikut.
"""

plt.figure(figsize=(6, 10))

order = df['NAMA_CABANG'].value_counts().index
sns.countplot(y='NAMA_CABANG', data=df, palette='viridis', order=order, legend=False)

plt.title('Persebaran Toko Berdasarkan Wilayah', fontsize=16)
plt.xlabel('Jumlah Toko', fontsize=12)
plt.ylabel('Wilayah', fontsize=12)

plt.show()

"""Berdasarkan diagram di atas, dapat dilihat bahwa persebaran toko di berbagai wilayah cukup beragam. Wilayah/cabang yang memiliki toko paling banyak adalah CILEUNGSI 2, sedangkan wilayah/cabang yang memiliki toko paling sedikit adalah PONTIANAK.

### Distribusi penyebab masalah pada setiap divisi



*   Apa penyebab masalah yang paling banyak dihadapi oleh masing-masing divisi?
*   Bagaimana distribusi penyebab masalah pada setiap divisi?
*   Divisi manakah yang menangani kasus masalah paling banyak?

Dibentuk beberapa tabel untuk melihat persebaran penyebab masalah pada masing-masing divisi.
"""

df_div_main = df[df['DIVISI'] == "MAINTENANCE"]
df_div_IT_opr_cab = df[df['DIVISI'] == "IT Opr Cabang"]
df_div_IT_bus_sol = df[df['DIVISI'] == "IT Bussines Solution"]
df_div_esvc = df[df['DIVISI'] == "E SERVICE"]
df_div_gen_svc = df[df['DIVISI'] == "GENERAL SERVICE"]
df_div_IT_opr_HO = df[df['DIVISI'] == "IT Opr HO"]
df_div_HCO = df[df['DIVISI'] == "HUMAN CAPITAL OPERATION"]
df_div_IC = df[df['DIVISI'] == "IC"]
df_div_MDC = df[df['DIVISI'] == "MD Category"]
df_div_IT_bus_int = df[df['DIVISI'] == "IT Bussines Intelegent"]
df_div_MP = df[df['DIVISI'] == "Marketing Promosi"]
df_div_log = df[df['DIVISI'] == "LOGISTIC"]
df_div_frc = df[df['DIVISI'] == "FRANCHISE"]
df_div_MDF = df[df['DIVISI'] == "MD Food"]
df_div_FR = df[df['DIVISI'] == "FINANCE REGULER"]
df_div_FF = df[df['DIVISI'] == "FINANCE FRANCHISE"]
df_div_MDFP = df[df['DIVISI'] == "MD Food Project"]

"""Dalam hal ini, diperlihatkan jumlah faktor masalah dari beberapa divisi saja.  """

df_div_main['FAKTOR_PROBLEM'].value_counts()

df_div_IC['FAKTOR_PROBLEM'].value_counts()

df_div_IT_opr_cab['FAKTOR_PROBLEM'].value_counts()

"""Diperhatikan untuk divisi MAINTENANCE, ada 3 penyebab masalah yang ditangani, dengan penyebab masalah tertinggi berupa LIFETIME. Untuk divisi IC dan IT Opr Cabang, penyebab masalah tertinggi secara berturut-turut adalah SYSTEM dan HARDWARE. Selanjutnya, ditampilkan diagram batang untuk melihat persebaran setiap divisi terhadap jumlah dan penyebab masalah."""

problem_distribution = df.groupby(['DIVISI', 'FAKTOR_PROBLEM']).size().unstack().fillna(0)
problem_distribution

problem_distribution["LIFETIME"]

problem_distribution.plot(kind='bar', stacked=True, figsize=(10, 6), cmap='Set2')

plt.title('Distribusi Faktor Masalah pada Masing-masing Divisi', fontsize=16)
plt.xlabel('Divisi', fontsize=12)
plt.ylabel('Jumlah Kasus', fontsize=12)

plt.legend(title='Faktor Problem', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""Melalui diagram di atas, persebaran masalah pada setiap divisi beragam, terdapat divisi yang paling banyak menangani kasus, serta terdapat pula divisi yang tidak menangani kasus sama sekali. Dapat dilihat bahwa kasus masalah paling banyak ditangani oleh divisi MAINTENANCE, dengan faktor masalah tertinggi berupa LIFETIME."""



"""### Analisis waktu penyelesaian masalah serta identifikasi faktor penyebab masalah



*   Bagaimana distribusi data waktu penyelesaian masalah untuk semua kategori? Apakah relatif cepat atau lambat?
*   Apa penyebab masalah yang memiliki frekuensi paling banyak atau paling sedikit?

Dibentuk histogram untuk melihat data persebaran waktu penyelesaian masalah.
"""

plt.figure(figsize=(10, 6))

sns.histplot(df['WAKTU_PENYELESAIAN'], bins=30, kde=True, color='skyblue')

plt.title('Distribusi Waktu Penyelesaian Masalah', fontsize=16)
plt.xlabel('Waktu Penyelesaian (hari)', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)


plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Setalah dilakukan proses binning (pembuatan kategori), maka diperoleh histogram sebagai berikut."""

plt.figure(figsize=(10, 6))

sns.histplot(df1, bins=30, kde=True, color='skyblue')

plt.title('Distribusi Waktu Penyelesaian Masalah (Setelah Proses Binning)', fontsize=16)
plt.xlabel('Range (hari)', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)


plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Berdasarkan dua histogram di atas, distribusi waktu penyelesaian masalah cenderung berada di range $0-5$ hari. Hal ini menjadi indikasi bahwa waktu penyelesaian masalah cenderung cepat dan tidak menunggu waktu selama lebih dari satu minggu. Hanya saja, ada beberapa kasus yang memang perlu waktu lebih dari satu minggu."""

plt.figure(figsize=(10, 6))

order = df['FAKTOR_PROBLEM'].value_counts().index
sns.countplot(y='FAKTOR_PROBLEM', data=df, palette='mako', order=order, legend=False)

plt.title('Data Penyebab Masalah', fontsize=16)
plt.xlabel('Frekuensi', fontsize=12)
plt.ylabel('Faktor Masalah', fontsize=12)

plt.show()

"""Kemudian, dibentuk diagram batang untuk melihat persebaran jumlah faktor masalah. Dapat dilihat bahwa penyebab masalah tertinggi berupa faktor LIFETIME yang berkisar di angka >17500 kasus, sedangkan penyebab masalah terendah berupa faktor SERVER HO.

### Analisis tingkat kepuasan dan pengaruh faktor masalah terhadap tingkat kepuasan



*   Bagaimana persentase atau perbandingan tingkat kepuasan pelanggan?
*   Bagaimana distribusi faktor masalah terhadap tingkat kepuasan pelanggan?

Diberikan diagram lingkaran untuk mengilustrasikan perbandingan tingkat kepuasan pelanggan.
"""

labels = [4,3,2,1]
sizes = df['TINGKAT_KEPUASAN'].value_counts()
colors = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue']
explode = (0.1, 0, 0, 0)

plt.pie(sizes, explode=explode, labels=labels, colors=colors,
        autopct='%1.1f%%', shadow=True, startangle=140)

plt.axis('equal')

plt.title('Tingkat Kepuasan Pelanggan')
plt.show()

"""Dari data yang diberikan, sebanyak $53.5\%$ pelanggan memberikan tingkat kepuasan $4$. Kemudian, $23.3\%$ pelanggan memberikan tingkat kepuasan $3$, $13.2\%$ pelanggan memberikan tingkat kepuasan $2$, dan yang paling rendah, $10.0\%$ pelanggan memberikan tingkat kepuassan $1$.


"""

plt.figure(figsize=(10, 6))

sns.boxplot(x='TINGKAT_KEPUASAN', y='FAKTOR_PROBLEM', data=df, palette='Set2', showmeans=True, meanline=True)

plt.title('Distribusi Tingkat Kepuasan Berdasarkan Faktor Masalah', fontsize=16)
plt.xlabel('Tingkat Kepuasan', fontsize=12)
plt.ylabel('Faktor Masalah', fontsize=12)
plt.show()

"""Selanjutnya, diperlihatkan box plot antara tingkat kepuasan pelanggan dengan faktor masalah. Berdasarkan data, distribusi antara tingkat kepuasan pelanggan dengan faktor masalah cenderung bervariasi. Jika dilihat berdasarkan rerata (mean), beberapa faktor masalah memiliki tingkat kepuasan yang rendah, seperti SERVER HO dan RUSAK BANGUNAN.

### Hubungan antara waktu penyelesaian masalah dengan tingkat kepuasan pelanggan

*   Bagaimana korelasi/hubungan antara waktu penyelesaian masalah dengan tingkat kepuasan pelanggan?

Terkait dengan data yang bersifat numerik, hubungan waktu penyelesaian masalah dengan tingkat kepuasan pelanggan dapat dilihat melalui perhitungan korelasi antara dua feature tersebut. Untuk melihat korelasi antara keduanya, maka diperlihatkan plot heatmap sebagai berikut.
"""

correlation = df[['WAKTU_PENYELESAIAN', 'TINGKAT_KEPUASAN']].corr()
sns.heatmap(correlation, annot=True)

"""Nilai korelasi antara waktu penyelesaian masalah dengan tingkat kepuasan pelanggan sebesar $-0.1$. Artinya, penyelesaian masalah sangat kontras (berbanding terbalik) dengan tingkat kepuasan pelanggan. Atau dengan kata lain, semakin besar waktu penyelesaian masalah (semakin lambat), semakin rendah pula tingkat kepuasan pelanggan.

### Perbandingan rata-rata tingkat kepuasan berdasarkan wilayah dan divisi

*   Wilayah/cabang manakah yang memiliki rata-rata tingkat kepuasan tertinggi/terendah?
*   Divisi manakah yang memiliki rata-rata tingkat kepuasan tertinggi/terendah?

Diberikan diagram batang untuk melihat rata-rata tingkat kepuasan berdasarkan wilayah dan divisi sebagai berikut.
"""

plt.figure(figsize=(6, 10))
mean_st = df.groupby('NAMA_CABANG')['TINGKAT_KEPUASAN'].mean().reset_index()
mean_st = mean_st.sort_values(by='TINGKAT_KEPUASAN', ascending=False)
sns.barplot(y='NAMA_CABANG', x='TINGKAT_KEPUASAN', data=mean_st, estimator='mean', palette='coolwarm')

plt.title('Rata-rata Tingkat Kepuasan Berdasarkan Wilayah', fontsize=16)
plt.ylabel('Wilayah', fontsize=12)
plt.xlabel('Rata-rata Tingkat Kepuasan', fontsize=12)
plt.show()

plt.figure(figsize=(6, 10))
mean_st = df.groupby('DIVISI')['TINGKAT_KEPUASAN'].mean().reset_index()
mean_st = mean_st.sort_values(by='TINGKAT_KEPUASAN', ascending=False)
sns.barplot(y='DIVISI', x='TINGKAT_KEPUASAN', data=mean_st, estimator='mean', palette='coolwarm')

plt.title('Rata-rata Tingkat Kepuasan Berdasarkan Divisi', fontsize=16)
plt.ylabel('Divisi', fontsize=12)
plt.xlabel('Rata-rata Tingkat Kepuasan', fontsize=12)
plt.show()

"""Berdasarkan diagram yang diberikan, wilayah/cabang yang memiliki rata-rata tingkat kepuasan tertinggi adalah PONTIANAK, sedangkan wilayah/cabang yang memiliki rata-rata tingkat kepuasan terendah adalah PLUMBON.

Selanjutnya, divisi yang memiliki rata-rata tingkat kepuasan tertinggi adalah IT Bussines Intelegent, sedangkan divisi yang memiliki rata-rata tingkat kepuasan terendah adalah FRANCHISE.
"""



"""## Konklusi

Dari beberapa feature yang dibahas, semua feature berperan penting dalam pengembangan dan perbaikan kualitas pelayanan toko kedepannya. Beberapa feature seperti tingkat kepuasan pelanggan, faktor masalah, wilayah/cabang, divisi, dan waktu penyelesaian masalah, memiliki pengaruh dalam kualitas pelayanan.  



1.   Persebaran toko pada setiap wilayah dan distribusi faktor masalah pada setiap divisi
* Berdasarkan visualisasi, persebaran toko di berbagai wilayah cukup beragam. Data wilayah/cabang yang memiliki toko paling banyak/paling sedikit dapat ditentukan melalui hasil visualisasi. Hal ini dapat menentukan kebijakan toko dalam mengembangkan kualitas pelayanan di suatu wilayah.
*Analisis distribusi faktor masalah berdasarkan divisi menunjukkan bahwa setiap divisi menghadapi masalah dengan intensitas yang berbeda. Terdapat satu divisi yang mendominasi distribusi masalah yaitu MAINTENANCE, sementara divisi lain menunjukkan distribusi masalah yang lebih merata. Divisi yang menangani lebih banyak masalah perlu ditinjau ulang untuk peningkatan efisiensi.
2.   Analisis waktu penyelesaian masalah serta identifikasi faktor penyebab masalah
* Untuk waktu penyelesaian masalah dari berbagai kategori tergolong cukup cepat. Hanya saja masih ada beberapa kategori masalah yang memerlukan waktu lebih lama untuk diselesaikan. Kemudian melalui visualisasi, frekuensi faktor masalah juga dapat diketahui. Faktor masalah yang paling banyak perlu diidentifikasi lebih lanjut sebagai prioritas untuk perbaikan.
3.   Analisis tingkat kepuasan dan pengaruh faktor masalah terhadap tingkat kepuasan pelanggan
* Proses analisis ini menghasilkan persentase tingkat kepuasan dan data persebaran tingkat kepuasan dengan faktor masalah. Dengan mengetahui persentase tingkat kepuasan dan keterkaitan antara faktor masalah, sebaiknya pihak divisi terkait perlu menetapkan prioritas untuk beberapa faktor masalah yang secara signifikan menurunkan tingkat kepuasan pelanggan.
4.   Hubungan antara waktu penyelesaian masalah dengan tingkat kepuasan pelanggan
* Terdapat hubungan negatif antara waktu penyelesaian masalah dan tingkat kepuasan pelanggan. Semakin lama waktu yang dibutuhkan untuk menyelesaikan masalah, semakin rendah tingkat kepuasan pelanggan. Ini menegaskan pentingnya respon cepat dalam menangani masalah pelanggan untuk menjaga tingkat kepuasan yang tinggi. Divisi yang memiliki waktu penyelesaian yang lama harus dievaluasi ulang untuk memperbaiki alur kerja dan meningkatkan kecepatan penanganan.
5.   Perbandingan rata-rata tingkat kepuasan berdasarkan wilayah dan divisi
* Berdasarkan hasil visualisasi, perbedaan rata-rata tingkat kepuasan berdasarkan wilayah cukup terlihat tetapi tidak terlalu drastis. Hal ini bisa disebabkan oleh berbagai faktor, seperti efisiensi penyelesaian masalah di wilayah tersebut atau kompleksitas masalah yang lebih rendah. Kemudian rata-rata tingkat kepuasan juga berbeda-beda antar divisi. Divisi yang memiliki rata-rata tingkat kepuasan yang lebih rendah perlu melakukan evaluasi lebih lanjut terhadap kinerja divisi tersebut, serta perlu adanya dukungan tambahan atau pelatihan untuk meningkatkan efisiensi dan kepuasan pelanggan.
"""

df.to_csv("dataset_final.csv")

